services:
  server-golang:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-golang
    restart: always
    volumes:
      - ./server:/app
    ports:
      - "50051:50051"
    networks:
      - custom_network


  mongo:
    image: mongo:8.0.4
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db
    networks:
      - custom_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "false"
    networks:
      - custom_network

volumes:
  mongo_data:

networks:
  custom_network:
    external: true

# go mod init chat-app
# go mod tidy
# go get go.mongodb.org/mongo-driver/v2/mongo